//! rxt 库：核心调度 + 标准库命令实现。
//!
//! 两个二进制：
//! - `rxt`：最小宿主（plugin/exec/info/version/upgrade/deploy/publish/sign）
//! - `rxt-tools`：其余命令，按插件单独安装/卸载

pub mod build;
pub mod callgraph;
pub mod cat;
pub mod check;
pub mod churn;
pub mod clean;
pub mod common;
pub mod count;
pub mod ctx;
pub mod cut;
pub mod dead;
pub mod dep;
pub mod describe;
pub mod diff;
pub mod digest;
pub mod edit;
pub mod enc;
pub mod exec;
pub mod find;
pub mod git;
pub mod grep;
pub mod hash;
pub mod hosts;
#[cfg(feature = "http")]
pub mod http;
#[cfg(not(feature = "http"))]
#[path = "http_stub.rs"]
pub mod http;
pub mod impact;
pub mod info;
pub mod jq;
pub mod jsonl;
pub mod langparse;
pub mod langs;
pub mod ls;
pub mod map;
#[cfg(feature = "http")]
pub mod mem;
#[cfg(not(feature = "http"))]
#[path = "mem_stub.rs"]
pub mod mem;
pub mod normalize;
pub mod pack;
pub mod patch;
pub mod publish;
pub mod py;
pub mod read;
pub mod refs;
pub mod remote;
pub mod replace;
pub mod search;
pub mod sed;
pub mod signature;
pub mod size;
pub mod sort;
pub mod stat;
pub mod storage;
#[path = "struct.rs"]
pub mod struct_mod;
pub mod tail;
pub mod timecmd;
pub mod trace;
pub mod tree;
pub mod uniq;
pub mod unzip;
pub mod uuidgen;
pub mod watch;
pub mod write;
// 系统命令族 (v0.4.0+) — 对标 PowerShell
pub mod net;
pub mod ps;
pub mod reg;
pub mod service;
pub mod sysinfo;
// 高效工具族 (v0.4.0+)
pub mod bench;
pub mod clip;
pub mod deploy;
pub mod dup;
pub mod evolve;
pub mod mcp;
pub mod notify;
pub mod plugin;
pub mod qr;
pub mod recipe;
pub mod repeat;
pub mod serve;
pub mod sign;
pub mod snapshot;
pub mod sync;
pub mod trash;
pub mod upgrade;
pub mod version;
pub mod watch_run;

pub mod core_cli;
pub mod tools_app;
